on:
  [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        # configuração versão do NODE encontrada em:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
        with:
          node-version: 12
